const Map<String, String> appStringsEn = {
  'appTitle': 'Travans',
  'authKicker': 'Welcome to Travans',
  'loginTitle': 'Sign in',
  'loginSubtitle':
      'Sign in to manage your training plan and Strava synchronization.',
  'registerTitle': 'Create account',
  'registerSubtitle':
      'Create an account to build your training plan and continue the mobile Travans experience.',
  'email': 'Email',
  'password': 'Password',
  'displayName': 'Display name',
  'rememberMe': 'Remember me',
  'signIn': 'Sign in',
  'signUp': 'Create account',
  'orSeparator': 'OR',
  'googleSignIn': 'Sign in with Google',
  'googleSignUp': 'Sign up with Google',
  'goToRegister': 'No account yet? Create one',
  'goToLogin': 'Already have an account? Sign in',
  'dashboard': 'Dashboard',
  'plans': 'Plans',
  'integrations': 'Integrations',
  'account': 'Account',
  'integrationsTitle': 'Strava connection',
  'integrationsSubtitle':
      'Connect your account, sync activities, and inspect matched workouts.',
  'integrationsConnectionTitle': 'Account connection',
  'integrationsConnected': 'Connected',
  'integrationsDisconnected': 'Disconnected',
  'integrationsConnectAction': 'Connect Strava',
  'integrationsSyncAction': 'Sync',
  'integrationsSyncing': 'Syncing...',
  'integrationsLastSync': 'Last sync',
  'integrationsAthleteId': 'Athlete ID',
  'integrationsActivitiesTitle': 'Activities imported from Strava',
  'integrationsFilterAll': 'All',
  'integrationsActivitiesEmpty': 'No imported activities for this filter.',
  'integrationsMatched': 'MATCHED',
  'integrationsUnmatched': 'UNMATCHED',
  'integrationsUnmatchedDescription':
      'This activity has not been linked to any training day yet.',
  'integrationsResultTitle': 'Sync result',
  'integrationsImportedActivities': 'Imported activities',
  'integrationsMatchedDays': 'Matched training days',
  'integrationsRedirectHint':
      'Connect Strava to download activities and sync them with your training plan.',
  'integrationsDistance': 'Distance',
  'integrationsDuration': 'Duration',
  'integrationsAverageSpeed': 'Average speed',
  'integrationsAveragePace': 'Average pace',
  'integrationsElevation': 'Elevation',
  'integrationsHeartRate': 'Heart rate',
  'integrationsMatchSection': 'Plan match',
  'integrationsActivityLoadError': 'Failed to load activity details.',
  'activityRun': 'Run',
  'activityRide': 'Ride',
  'activitySwim': 'Swim',
  'activityWalk': 'Walk',
  'activityWorkout': 'Workout',
  'activityStrength': 'Strength',
  'activityOther': 'Other activity',
  'logout': 'Log out',
  'language': 'Language',
  'tryAgain': 'Try again',
  'loading': 'Loading...',
  'requiredField': 'This field is required.',
  'invalidEmail': 'Enter a valid email address.',
  'passwordTooShort': 'Password must be at least 8 characters.',
  'genericAuthError': 'Authentication request failed.',
  'dashboardPlaceholder':
      'Dashboard with plan progress and stats will live here.',
  'plansPlaceholder': 'Plans list and editor will live here.',
  'integrationsPlaceholder': 'Strava integration will live here.',
  'accountPlaceholder': 'User profile will live here.',
  'sessionExpired': 'Your session expired. Sign in again.',
  'welcomeBack': 'You already have the mobile app foundation in place.',
  'switchLanguage': 'Switch language',
  'shellOpenMenu': 'Open menu',
  'shellNavigation': 'Navigation',
  'shellQuickActions': 'Quick actions',
  'shellSignedInAs': 'Signed in as',
  'shellNotConnected': 'No active Strava connection',
  'shellGoToAccount': 'Go to account',
  'shellSectionDashboard': 'Overview',
  'shellSectionPlans': 'Training plans',
  'shellSectionIntegrations': 'Connections',
  'shellSectionAccount': 'Profile and session',
  'emptyStateTitle': 'Nothing here yet',
  'errorStateTitle': 'Something went wrong',
  'pullToRefresh': 'Pull to refresh',
  'accountSectionLanguage': 'Language',
  'accountSectionSession': 'Session',
  'accountConnectedProvider': 'Connected provider',
  'accountOpenProfile': 'Account settings will be expanded in the next sprint.',
  'authProviderLocal': 'Email and password',
  'authProviderGoogle': 'Google',
  'invalidActivityId': 'Invalid activity id',
  'trainingStatusPlanned': 'Planned',
  'trainingStatusCompleted': 'Completed',
  'trainingStatusPartial': 'Partial',
  'trainingStatusMissed': 'Missed',
  'dashboardHeaderKicker': 'Dashboard',
  'dashboardHeaderTitle': 'Plan completion progress',
  'dashboardDisplayedPlan': 'Displayed plan',
  'dashboardAutoSelect': 'Automatically selected',
  'dashboardLoading': 'Loading dashboard data...',
  'dashboardStatsPlanned': 'Planned',
  'dashboardStatsCompleted': 'Completed',
  'dashboardStatsPartial': 'Partial',
  'dashboardStatsMissed': 'Missed',
  'dashboardStatsEffectiveness': 'Effectiveness',
  'dashboardDetailsLabel': 'Detailed stats',
  'dashboardDaysMeetingDistanceGoal': 'Days meeting distance goal',
  'dashboardDaysMeetingDurationGoal': 'Days meeting duration goal',
  'dashboardDaysMeetingPaceGoal': 'Days meeting pace goal',
  'dashboardAverageRunPace': 'Average run pace',
  'dashboardFastestRunPace': 'Fastest run pace',
  'dashboardAverageRideSpeed': 'Average ride speed',
  'dashboardMaxRideSpeed': 'Max ride speed',
  'dashboardElevationGain': 'Elevation gain',
  'dashboardCurrentPlanLabel': 'Current plan',
  'dashboardCurrentPlanEmptyTitle': 'No active plan',
  'dashboardCurrentPlanEmptyDescription':
      'Add a training plan and the dashboard will start showing progress and matched Strava workouts.',
  'dashboardPlanTypePrefix': 'Plan type:',
  'dashboardPinnedMessage': 'The plan has been pinned to the dashboard.',
  'dashboardScheduledFor': 'Scheduled for',
  'dashboardActivity': 'Activity',
  'dashboardPlannedSection': 'Plan',
  'dashboardCompletedSection': 'Completed',
  'dashboardMatchedActivity': 'Matched activity:',
  'dashboardNotes': 'Notes',
  'dashboardDistanceGoal': 'Distance goal',
  'dashboardDurationGoal': 'Duration goal',
  'dashboardPaceGoal': 'Pace goal',
  'dashboardAverageSpeed': 'Average speed',
  'dashboardMaxSpeed': 'Max speed',
  'dashboardAverageHeartrate': 'Average heart rate',
  'dashboardMaxHeartrate': 'Max heart rate',
  'dashboardAverageCadence': 'Average cadence',
  'dashboardOverDistance': 'Distance surplus',
  'dashboardOverDuration': 'Time surplus',
  'dashboardSavedTime': 'Time saved',
  'dashboardGoalAchieved': 'Achieved',
  'dashboardGoalNotAchieved': 'Not achieved',
  'dashboardNoCriteria': 'No criteria',
  'dashboardNoTrainingDays': 'This plan does not have any training days yet.',
  'plansLoading': 'Loading plans list...',
  'plansHeaderKicker': 'Plans',
  'plansHeaderTitle': 'Your training plans',
  'plansHeaderSubtitleZero': 'You do not have any plans yet.',
  'plansHeaderSubtitleOne': 'You have 1 saved training plan.',
  'plansHeaderSubtitleMany': 'You have {count} saved training plans.',
  'plansCreateAction': 'New plan',
  'plansEmptyTitle': 'No training plans',
  'plansEmptyDescription':
      'Once you add your first plan, you will see its details and training days here.',
  'plansTypeLabel': 'Type',
  'plansDaysLabel': 'Days',
  'plansStartDateLabel': 'Start',
  'plansCreatedAtLabel': 'Created at',
  'plansDescriptionLabel': 'Description',
  'plansDaysSection': 'Training days',
  'plansNoTrainingDays': 'This plan does not define any training days yet.',
  'plansVisibleOnDashboard': 'On dashboard',
  'plansShowOnDashboard': 'Show on dashboard',
  'plansDelete': 'Delete',
  'plansCancel': 'Cancel',
  'plansDayPrefix': 'Day',
  'plansDistanceLabel': 'Distance',
  'plansDurationLabel': 'Duration',
  'plansNotesLabel': 'Notes',
  'plansMatchedActivityLabel': 'Matched activity',
  'plansPinDialogTitle': 'Show this plan on the dashboard?',
  'plansPinDialogMessage':
      'The "{name}" plan will be pinned as the primary dashboard view.',
  'plansDeleteDialogTitle': 'Delete plan?',
  'plansDeleteDialogMessage':
      'The "{name}" plan will be permanently removed together with its training days.',
  'plansPinnedSnackbar': 'The "{name}" plan is now visible on the dashboard.',
  'plansDeletedSnackbar': 'The "{name}" plan has been deleted.',
  'plansCreatedSnackbar': 'The "{name}" plan has been created.',
  'plansUpdatedSnackbar': 'The "{name}" plan has been updated.',
  'plansCreateTitle': 'New training plan',
  'plansEditTitle': 'Edit training plan',
  'plansCreateSubtitle':
      'Build a plan, add training days, and prepare it for Strava analysis.',
  'plansEditSubtitle':
      'Update plan details and reorder training days without leaving the app.',
  'plansEditorKicker': 'Plan editor',
  'plansEditorLoading': 'Loading plan form...',
  'plansEditorSectionPlan': 'Plan details',
  'plansEditorSectionDays': 'Training days',
  'plansEditorSectionImport': 'JSON import',
  'plansEditorDaysHint':
      'Set the order of days, schedule dates, and planned workout values.',
  'plansEditorAddDay': 'Add day',
  'plansEditorAtLeastOneDay':
      'A plan must contain at least one training day.',
  'plansEditorName': 'Plan name',
  'plansEditorDescription': 'Description',
  'plansEditorStartDate': 'Start date',
  'plansEditorStravaStartDate': 'Strava evaluation start',
  'plansEditorPlanType': 'Plan type',
  'plansEditorDayDate': 'Schedule date',
  'plansEditorDayTitle': 'Workout title',
  'plansEditorDayActivityType': 'Activity type',
  'plansEditorDayDistance': 'Planned distance (m)',
  'plansEditorDayDuration': 'Planned duration (s)',
  'plansEditorDayNotes': 'Notes',
  'plansEditorValidationError':
      'Fill in the required plan fields and all required training day fields.',
  'plansEditorInvalidNumber':
      'Enter a valid positive number or leave the field empty.',
  'plansSavePlan': 'Save plan',
  'plansSaveChanges': 'Save changes',
  'plansInvalidPlanId': 'Invalid plan id',
  'plansImportTitle': 'Load a plan from a JSON file',
  'plansImportDescription':
      'Choose a `.json` file, review the preview, and fill the form without editing raw text manually.',
  'plansImportPickFile': 'Choose JSON file',
  'plansImportSelectedFile': 'Selected file',
  'plansImportPreviewTitle': 'Import preview',
  'plansImportApply': 'Load into form',
  'plansImportReplaceNotice':
      'Import will replace the current form data with the new plan.',
  'plansImportNoPreview': 'A plan preview will appear here after choosing a file.',
  'plansImportInvalidFile': 'Choose a JSON file with the .json extension.',
  'plansImportReadError': 'Could not read the JSON file.',
  'plansImportInvalidJson': 'The JSON file has invalid syntax.',
  'plansImportValidationError':
      'The JSON file does not contain a complete training plan.',
  'plansImportApplied': 'The file data has been loaded into the form.',
  'plansImportPreviewDescription': 'Description',
  'plansImportPreviewDays': 'Days count',
  'plansImportPreviewType': 'Plan type',
  'plansImportPreviewStart': 'Start',
  'plansImportPreviewStravaStart': 'Strava evaluation start',
  'plansImportPreviewDaysSection': 'First training days',
  'plansImportPreviewMoreDays': '... and {count} more days',
  'errorAuthSessionExpired': 'Your session expired. Sign in again.',
  'errorAuthLoginFailed': 'Sign in failed.',
  'errorAuthRegisterFailed': 'Registration failed.',
  'errorAuthGoogleFailed': 'Google sign-in failed.',
  'errorGoogleSignInCanceled': 'Google sign-in was canceled.',
  'errorGoogleIdTokenMissing': 'Google did not return an ID token.',
  'errorGenericTaskFailed': 'The operation could not be completed.',
  'errorGoogleNetwork': 'A network error occurred during Google sign-in. Try again.',
  'errorGoogleAndroidConfig':
      'Google sign-in is not configured correctly for Android. Check package name, SHA-1, and OAuth client in Google Cloud.',
  'errorGoogleRestartRequired': 'Google sign-in needs to be started again.',
  'errorGooglePlatform': 'Google sign-in ended with a platform error.',
  'errorDashboardPlansLoad': 'Failed to load plans list.',
  'errorDashboardSummaryLoad': 'Failed to load dashboard data.',
  'errorPlansListLoad': 'Failed to load plans list.',
  'errorPlanLoad': 'Failed to load plan.',
  'errorPlanCreate': 'Failed to create plan.',
  'errorPlanUpdate': 'Failed to save plan changes.',
  'errorPlanDelete': 'Failed to delete plan.',
  'errorStravaStatusLoad': 'Failed to load Strava status.',
  'errorStravaActivitiesLoad': 'Failed to load Strava activities.',
  'errorStravaActivityLoad': 'Failed to load activity details.',
  'errorStravaExchange': 'Failed to complete Strava authorization.',
  'errorStravaSync': 'Failed to sync activities.',
  'errorStravaOpenLogin': 'Failed to open Strava sign-in.',
  'errorStravaAuthorizationDenied':
      'Strava authorization was canceled or denied.',
  'helloUser': 'Hello, {name}',
};
