const Map<String, String> appStringsPl = {
  'appTitle': 'Travans',
  'authKicker': 'Witaj w Travans',
  'loginTitle': 'Logowanie',
  'loginSubtitle':
      'Zaloguj się, aby zarządzać planem treningowym i synchronizacją Stravy.',
  'registerTitle': 'Załóż konto',
  'registerSubtitle':
      'Utwórz konto, aby budować plan treningowy i rozwijać mobilną wersję Travans.',
  'email': 'Email',
  'password': 'Hasło',
  'displayName': 'Nazwa użytkownika',
  'rememberMe': 'Zapamiętaj mnie',
  'signIn': 'Zaloguj',
  'signUp': 'Załóż konto',
  'orSeparator': 'LUB',
  'googleSignIn': 'Zaloguj się przez Google',
  'googleSignUp': 'Zarejestruj się przez Google',
  'goToRegister': 'Nie masz konta? Utwórz je',
  'goToLogin': 'Masz już konto? Zaloguj się',
  'dashboard': 'Dashboard',
  'plans': 'Plany',
  'integrations': 'Integracje',
  'account': 'Konto',
  'integrationsTitle': 'Połączenie ze Stravą',
  'integrationsSubtitle':
      'Połącz konto, synchronizuj aktywności i sprawdzaj dopasowane treningi.',
  'integrationsConnectionTitle': 'Połączenie konta',
  'integrationsConnected': 'Połączono',
  'integrationsDisconnected': 'Nie połączono',
  'integrationsConnectAction': 'Połącz ze Stravą',
  'integrationsSyncAction': 'Synchronizuj',
  'integrationsSyncing': 'Synchronizacja...',
  'integrationsLastSync': 'Ostatnia synchronizacja',
  'integrationsAthleteId': 'ID atleta',
  'integrationsActivitiesTitle': 'Treningi pobrane ze Stravy',
  'integrationsFilterAll': 'Wszystkie',
  'integrationsActivitiesEmpty': 'Brak pobranych aktywności dla tego filtra.',
  'integrationsMatched': 'DOPASOWANO',
  'integrationsUnmatched': 'BEZ DOPASOWANIA',
  'integrationsUnmatchedDescription':
      'Ta aktywność nie została jeszcze powiązana z żadnym dniem planu.',
  'integrationsResultTitle': 'Wynik synchronizacji',
  'integrationsImportedActivities': 'Zaimportowane aktywności',
  'integrationsMatchedDays': 'Dopasowane dni treningowe',
  'integrationsRedirectHint':
      'Połącz Stravę, aby pobierać aktywności i synchronizować je z planem treningowym.',
  'integrationsDistance': 'Dystans',
  'integrationsDuration': 'Czas',
  'integrationsAverageSpeed': 'Średnia prędkość',
  'integrationsAveragePace': 'Średnie tempo',
  'integrationsElevation': 'Przewyższenie',
  'integrationsHeartRate': 'Tętno',
  'integrationsMatchSection': 'Dopasowanie do planu',
  'integrationsActivityLoadError':
      'Nie udało się pobrać szczegółów aktywności.',
  'activityRun': 'Bieg',
  'activityRide': 'Rower',
  'activitySwim': 'Pływanie',
  'activityWalk': 'Marsz',
  'activityWorkout': 'Trening',
  'activityStrength': 'Siłownia',
  'activityOther': 'Inna aktywność',
  'logout': 'Wyloguj',
  'language': 'Język',
  'tryAgain': 'Spróbuj ponownie',
  'loading': 'Ładowanie...',
  'requiredField': 'To pole jest wymagane.',
  'invalidEmail': 'Podaj poprawny adres email.',
  'passwordTooShort': 'Hasło musi mieć co najmniej 8 znaków.',
  'genericAuthError': 'Nie udało się wykonać operacji autoryzacji.',
  'dashboardPlaceholder':
      'Tu pojawi się dashboard z planem i statystykami.',
  'plansPlaceholder': 'Tu pojawi się lista planów i edytor.',
  'integrationsPlaceholder': 'Tu pojawi się integracja ze Stravą.',
  'accountPlaceholder': 'Tu pojawi się profil użytkownika.',
  'sessionExpired': 'Sesja wygasła. Zaloguj się ponownie.',
  'welcomeBack': 'Masz już gotowy fundament aplikacji mobilnej.',
  'switchLanguage': 'Przełącz język',
  'shellOpenMenu': 'Otwórz menu',
  'shellNavigation': 'Nawigacja',
  'shellQuickActions': 'Szybkie akcje',
  'shellSignedInAs': 'Zalogowano jako',
  'shellNotConnected': 'Brak aktywnego połączenia ze Stravą',
  'shellGoToAccount': 'Przejdź do konta',
  'shellSectionDashboard': 'Podsumowanie',
  'shellSectionPlans': 'Plany treningowe',
  'shellSectionIntegrations': 'Połączenia',
  'shellSectionAccount': 'Profil i sesja',
  'emptyStateTitle': 'Jeszcze nic tu nie ma',
  'errorStateTitle': 'Coś poszło nie tak',
  'pullToRefresh': 'Pociągnij, aby odświeżyć',
  'accountSectionLanguage': 'Język',
  'accountSectionSession': 'Sesja',
  'accountConnectedProvider': 'Metoda logowania',
  'accountOpenProfile':
      'Ustawienia konta rozszerzymy w kolejnym sprincie.',
  'authProviderLocal': 'Email i hasło',
  'authProviderGoogle': 'Google',
  'invalidActivityId': 'Nieprawidłowe id aktywności',
  'trainingStatusPlanned': 'Zaplanowane',
  'trainingStatusCompleted': 'Wykonane',
  'trainingStatusPartial': 'Częściowo',
  'trainingStatusMissed': 'Pominięte',
  'dashboardHeaderKicker': 'Pulpit',
  'dashboardHeaderTitle': 'Postęp realizacji planu',
  'dashboardDisplayedPlan': 'Wyświetlany plan',
  'dashboardAutoSelect': 'Automatycznie wybrany',
  'dashboardLoading': 'Ładowanie danych dashboardu...',
  'dashboardStatsPlanned': 'Zaplanowane',
  'dashboardStatsCompleted': 'Wykonane',
  'dashboardStatsPartial': 'Częściowo',
  'dashboardStatsMissed': 'Pominięte',
  'dashboardStatsEffectiveness': 'Skuteczność',
  'dashboardDetailsLabel': 'Statystyki szczegółowe',
  'dashboardDaysMeetingDistanceGoal': 'Dni z celem dystansu',
  'dashboardDaysMeetingDurationGoal': 'Dni z celem czasu',
  'dashboardDaysMeetingPaceGoal': 'Dni z celem tempa',
  'dashboardAverageRunPace': 'Średnie tempo biegu',
  'dashboardFastestRunPace': 'Najszybsze tempo biegu',
  'dashboardAverageRideSpeed': 'Średnia prędkość jazdy',
  'dashboardMaxRideSpeed': 'Maksymalna prędkość jazdy',
  'dashboardElevationGain': 'Przewyższenie',
  'dashboardCurrentPlanLabel': 'Bieżący plan',
  'dashboardCurrentPlanEmptyTitle': 'Brak aktywnego planu',
  'dashboardCurrentPlanEmptyDescription':
      'Dodaj plan treningowy, a dashboard zacznie pokazywać postęp i dopasowane treningi ze Stravy.',
  'dashboardPlanTypePrefix': 'Typ planu:',
  'dashboardPinnedMessage': 'Plan został przypięty do dashboardu.',
  'dashboardScheduledFor': 'Termin',
  'dashboardActivity': 'Aktywność',
  'dashboardPlannedSection': 'Plan',
  'dashboardCompletedSection': 'Wykonanie',
  'dashboardMatchedActivity': 'Powiązana aktywność:',
  'dashboardNotes': 'Notatki',
  'dashboardDistanceGoal': 'Cel dystansu',
  'dashboardDurationGoal': 'Cel czasu',
  'dashboardPaceGoal': 'Cel tempa',
  'dashboardAverageSpeed': 'Średnia prędkość',
  'dashboardMaxSpeed': 'Maks. prędkość',
  'dashboardAverageHeartrate': 'Średnie tętno',
  'dashboardMaxHeartrate': 'Maks. tętno',
  'dashboardAverageCadence': 'Średnia kadencja',
  'dashboardOverDistance': 'Nadwyżka dystansu',
  'dashboardOverDuration': 'Nadwyżka czasu',
  'dashboardSavedTime': 'Zysk czasu',
  'dashboardGoalAchieved': 'Osiągnięto',
  'dashboardGoalNotAchieved': 'Nie osiągnięto',
  'dashboardNoCriteria': 'Brak kryterium',
  'dashboardNoTrainingDays': 'Ten plan nie ma jeszcze dni treningowych.',
  'plansLoading': 'Ładowanie listy planów...',
  'plansHeaderKicker': 'Plany',
  'plansHeaderTitle': 'Twoje plany treningowe',
  'plansHeaderSubtitleZero': 'Nie masz jeszcze żadnych planów.',
  'plansHeaderSubtitleOne': 'Masz 1 zapisany plan treningowy.',
  'plansHeaderSubtitleMany': 'Masz {count} zapisanych planów treningowych.',
  'plansCreateAction': 'Nowy plan',
  'plansEmptyTitle': 'Brak planów treningowych',
  'plansEmptyDescription':
      'Gdy dodasz pierwszy plan, zobaczysz tu jego szczegóły i dni treningowe.',
  'plansTypeLabel': 'Typ',
  'plansDaysLabel': 'Dni',
  'plansStartDateLabel': 'Start',
  'plansCreatedAtLabel': 'Utworzono',
  'plansDescriptionLabel': 'Opis',
  'plansDaysSection': 'Dni treningowe',
  'plansNoTrainingDays': 'Ten plan nie ma jeszcze zdefiniowanych dni.',
  'plansVisibleOnDashboard': 'Na dashboardzie',
  'plansShowOnDashboard': 'Pokaż na dashboardzie',
  'plansDelete': 'Usuń',
  'plansCancel': 'Anuluj',
  'plansDayPrefix': 'Dzień',
  'plansDistanceLabel': 'Dystans',
  'plansDurationLabel': 'Czas',
  'plansNotesLabel': 'Notatki',
  'plansMatchedActivityLabel': 'Powiązana aktywność',
  'plansPinDialogTitle': 'Wyświetlać ten plan na dashboardzie?',
  'plansPinDialogMessage':
      'Plan "{name}" zostanie przypięty jako główny widok na dashboardzie.',
  'plansDeleteDialogTitle': 'Usunąć plan?',
  'plansDeleteDialogMessage':
      'Plan "{name}" zostanie trwale usunięty wraz z listą dni treningowych.',
  'plansPinnedSnackbar': 'Plan "{name}" jest teraz widoczny na dashboardzie.',
  'plansDeletedSnackbar': 'Plan "{name}" został usunięty.',
  'plansCreatedSnackbar': 'Plan "{name}" został utworzony.',
  'plansUpdatedSnackbar': 'Plan "{name}" został zaktualizowany.',
  'plansCreateTitle': 'Nowy plan treningowy',
  'plansEditTitle': 'Edytuj plan treningowy',
  'plansCreateSubtitle':
      'Zbuduj plan, dodaj dni treningowe i przygotuj go pod analizę Stravy.',
  'plansEditSubtitle':
      'Zmień dane planu i uporządkuj dni treningowe bez wychodzenia z aplikacji.',
  'plansEditorKicker': 'Edytor planu',
  'plansEditorLoading': 'Ładowanie formularza planu...',
  'plansEditorSectionPlan': 'Dane planu',
  'plansEditorSectionDays': 'Dni treningowe',
  'plansEditorDaysHint':
      'Ustaw kolejność dni, terminy i planowane wartości treningowe.',
  'plansEditorAddDay': 'Dodaj dzień',
  'plansEditorAtLeastOneDay':
      'Plan musi zawierać co najmniej jeden dzień treningowy.',
  'plansEditorName': 'Nazwa planu',
  'plansEditorDescription': 'Opis',
  'plansEditorStartDate': 'Data startu',
  'plansEditorStravaStartDate': 'Start oceny Strava',
  'plansEditorPlanType': 'Typ planu',
  'plansEditorDayDate': 'Termin',
  'plansEditorDayTitle': 'Tytuł treningu',
  'plansEditorDayActivityType': 'Typ aktywności',
  'plansEditorDayDistance': 'Planowany dystans (m)',
  'plansEditorDayDuration': 'Planowany czas (s)',
  'plansEditorDayNotes': 'Notatki',
  'plansEditorValidationError':
      'Uzupełnij wymagane pola planu i wszystkich dni treningowych.',
  'plansEditorInvalidNumber':
      'Podaj poprawną liczbę dodatnią lub zostaw pole puste.',
  'plansSavePlan': 'Zapisz plan',
  'plansSaveChanges': 'Zapisz zmiany',
  'plansInvalidPlanId': 'Nieprawidłowe id planu',
  'errorAuthSessionExpired': 'Sesja wygasła. Zaloguj się ponownie.',
  'errorAuthLoginFailed': 'Logowanie nie powiodło się.',
  'errorAuthRegisterFailed': 'Rejestracja nie powiodła się.',
  'errorAuthGoogleFailed': 'Logowanie Google nie powiodło się.',
  'errorGoogleSignInCanceled': 'Logowanie Google zostało anulowane.',
  'errorGoogleIdTokenMissing': 'Google nie zwrócił tokena ID.',
  'errorGenericTaskFailed': 'Nie udało się wykonać zadania.',
  'errorGoogleNetwork': 'Błąd sieci podczas logowania Google. Spróbuj ponownie.',
  'errorGoogleAndroidConfig':
      'Logowanie Google nie jest poprawnie skonfigurowane dla Androida. Sprawdź package name, SHA-1 i OAuth client w Google Cloud.',
  'errorGoogleRestartRequired':
      'Wymagane jest ponowne uruchomienie logowania Google.',
  'errorGooglePlatform': 'Logowanie Google zakończyło się błędem platformy.',
  'errorDashboardPlansLoad': 'Nie udało się pobrać listy planów.',
  'errorDashboardSummaryLoad': 'Nie udało się pobrać danych dashboardu.',
  'errorPlansListLoad': 'Nie udało się pobrać listy planów.',
  'errorPlanLoad': 'Nie udało się pobrać planu.',
  'errorPlanCreate': 'Nie udało się utworzyć planu.',
  'errorPlanUpdate': 'Nie udało się zapisać zmian planu.',
  'errorPlanDelete': 'Nie udało się usunąć planu.',
  'errorStravaStatusLoad': 'Nie udało się pobrać statusu Stravy.',
  'errorStravaActivitiesLoad': 'Nie udało się pobrać aktywności ze Stravy.',
  'errorStravaActivityLoad': 'Nie udało się pobrać szczegółów aktywności.',
  'errorStravaExchange': 'Nie udało się zakończyć autoryzacji Stravy.',
  'errorStravaSync': 'Nie udało się zsynchronizować aktywności.',
  'errorStravaOpenLogin': 'Nie udało się otworzyć logowania Stravy.',
  'errorStravaAuthorizationDenied':
      'Autoryzacja Stravy została anulowana lub odrzucona.',
  'helloUser': 'Witaj, {name}',
};
